def instructions():
    print()
    print("|+=--         How to play 'Risk of Rain'          --=+|")
    print("|+=--                                             --=+|")
    print("|+=--       1. select a difficulty out of 3       --=+|")
    print("|+=--    'drizzle'     'rainstorm'    'monsoon'   --=+|")
    print("|+=--                                             --=+|")
    print("|+=--   2. choose how many questions to answer    --=+|")
    print("|+=--     answering faster and playing harder     --=+|")
    print("|+=--       difficulties grants more points       --=+|")
    print("|+=--                                             --=+|")
    print("|+=--     3. if you want to quit type 'xxx'       --=+|")
    print("|+=--   and once youve completed the questions    --=+|")
    print("|+=--  you can play again and try to do better    --=+|")
    print("|+=--                                             --=+|")